# Generated by Django 3.0.8 on 2020-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200804_1344'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='village',
        ),
        migrations.AddField(
            model_name='person',
            name='villages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'row__table__id': 14}, related_name='users', to='main.Cell', verbose_name='Населенные пункты'),
        ),
    ]
