# Generated by Django 3.0.8 on 2020-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200901_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_regional',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Главный оператор'),
        ),
    ]
