# Generated by Django 3.1.1 on 2020-09-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_person_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
    ]
