# Generated by Django 3.0.8 on 2020-07-24 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Идентификатор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Table', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Row', verbose_name='Родитель')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Table', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Строка',
                'verbose_name_plural': 'Строки',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('brief_name', models.CharField(max_length=50, verbose_name='Краткое наименование')),
                ('decimal_places', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Кол-во знаков после запятой')),
                ('column_type', models.IntegerField(choices=[(1, 'Логическое'), (2, 'Целое число'), (3, 'Дробное число'), (4, 'Краткая дата'), (5, 'Дата'), (6, 'Текст'), (7, 'Строка 50 символов'), (8, 'Строка 200 символов'), (9, 'Ссылка'), (10, 'Формула')], default=2, verbose_name='Тип')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Table', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Столбец',
                'verbose_name_plural': 'Столбцы',
            },
        ),
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='Значение')),
                ('float_value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='Значение')),
                ('text_value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('char50_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Значение')),
                ('char200_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Значение')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='Значение')),
                ('formula_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение')),
                ('ref_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Row', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение ячейки',
                'verbose_name_plural': 'Значения ячеек',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Column', verbose_name='Колонка')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Row', verbose_name='Строка')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CellValue', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'unique_together': {('col', 'row')},
            },
        ),
    ]
