# Generated by Django 3.0.8 on 2020-08-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200804_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CellValue', verbose_name='Значение'),
        ),
    ]
