# Generated by Django 3.0.8 on 2020-09-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200903_1602'),
        ('main', '0007_column_use_in_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report', verbose_name='Отчет'),
        ),
    ]
