# Generated by Django 3.0.8 on 2020-09-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_row_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'row__table__name': 'Группы показателей'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Cell', verbose_name='Группа'),
        ),
    ]
