# Generated by Django 3.0.8 on 2020-07-24 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Редактируется'), (2, 'Готов к проверке'), (3, 'Проверяется'), (4, 'Согласовано'), (5, 'На доработку')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отчета')),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethnicity_reports', to='main.Row', verbose_name='КМНС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person', verbose_name='Пользователь')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_reports', to='main.Row', verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
