# Generated by Django 3.0.8 on 2020-09-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='village',
        ),
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.CharField(default='', max_length=250, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
