# Generated by Django 3.0.8 on 2020-09-06 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200903_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.IntegerField(choices=[(6, 'Новый'), (1, 'Редактируется'), (2, 'Готов к проверке'), (3, 'Проверяется'), (4, 'Согласовано'), (5, 'На доработку')], default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Состояние'),
        ),
    ]
