# Generated by Django 3.0.8 on 2020-09-07 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200907_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Дата отчета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
