# Generated by Django 3.0.8 on 2020-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200907_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(db_index=True, verbose_name='Дата отчета'),
        ),
    ]
