# Generated by Django 3.0.8 on 2020-09-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200907_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_date1',
            new_name='report_date',
        ),
    ]
