# Generated by Django 3.1.1 on 2020-09-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200907_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Комментарии'),
        ),
    ]
