# Generated by Django 3.0.8 on 2020-07-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(0, 'Ничего не сделано'), (1, 'Добавлено'), (2, 'Отредактировано'), (3, 'Удалено'), (4, 'Загружено'), (5, 'Выгружено')], default=0, verbose_name='Операция')),
                ('log_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('child_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_logs', to='contenttypes.ContentType', verbose_name='Дочерний объект')),
                ('parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_logs', to='contenttypes.ContentType', verbose_name='Объект родитель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в журнал',
                'verbose_name_plural': 'Журнал действий',
            },
        ),
    ]
